### ISSUE TITLE
test_server crashes except when RUST_BACKTRACE=full

### ISSUE THREAD

**Issue by potto216** [potto216/BlueR-Test#5] opened 2022-01-27 01:02 UTC
The [test_server](https://github.com/potto216/BlueR-Test/tree/main/test_server) crashes as shown below except when RUST_BACKTRACE=full. When RUST_BACKTRACE isn't set and you run test_server then test_client you get:
```
user@bluedev:~/src-rust/bluer-test/test_server$ unset RUST_BACKTRACE
user@bluedev:~/src-rust/bluer-test/test_server$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `/home/user/src-rust/bluer-test/target/debug/test_server`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Receive(ChMux)', test_server/src/main.rs:53:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When you run RUST_BACKTRACE=1 you get
[test_server_RUST_BACKTRACE_1.txt](https://github.com/potto216/BlueR-Test/files/7946675/test_server_RUST_BACKTRACE_1.txt)

But when RUST_BACKTRACE=full it works and you get
[test_server_RUST_BACKTRACE_full.txt](https://github.com/potto216/BlueR-Test/files/7946676/test_server_RUST_BACKTRACE_full.txt)

test_server and test_trace were created by splitting the [example](https://github.com/ENQT-GmbH/remoc)

**Comment by surban** [comment] 2022-01-27 09:46
This is caused by the client exiting before closing the connection.

Connection shutdown starts when `tx` and `_rx` are dropped when the `connect_client` function is exited. However, this is done in a background task, so `main` exits first and the process is terminated and with it the TCP connection. Thus, the server sees a connection error instead of a graceful shutdown. However, this is harmless and you can safely ignore it.

Change https://github.com/potto216/BlueR-Test/blob/035d3e1979bb65069fda7b78527baa8bbae0be8a/test_server/src/main.rs#L53 to
`while let Ok(Some(CountReq {up_to, seq_tx})) = rx.recv().await`
to ignore the error.

Yesterday I've created a [sample project for RTC communication](https://github.com/ENQT-GmbH/remoc/tree/master/examples/rtc). I would suggest that you start with it, instead of the samples from the documentation.

**Comment by potto216** [comment] 2022-01-27 10:50
Thanks for the explanation! I'll switch over the code to what's in the sample RTC project and try that.

**Closed as completed** 2022-01-29 20:00 UTC
